global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: [':9100']    

  - job_name: 'jenkins'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['<your-jenkins-ip>:<your-jenkins-port>']
      
  - job_name: 'app' 
    metrics_path: '/metrics'
    static_configs:
      - targets: ['node-exporter-IP:9100']
