global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['<change-monioring-IP-here>:9100']
      - targets: ['<main-server-IP-here>:9100']

  - job_name: 'jenkins'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['<your-jenkins-ip>:<your-jenkins-port>']
      
  - job_name: 'app' 
    metrics_path: '/metrics'
    static_configs:
      - targets: ['node-exporter-IP:9100']

  - job_name: 'cAdvisor'
    static_configs:
      - targets: ['<change-monioring-IP-here>:8080']

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['<change-monioring-IP-here>:9093']    
      
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://prometheus.io  # Target to probe with http.
        - https://prometheus.io  # Target to probe with http.
        - http://app-running-ip-&-port-here # For Example:- 13.224.76.88:8080 or kubernetes port eg:- 30119 # Target to probe with http on port 8080. 
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: <change-monitoring-ip-here>:9115  # The blackbox exporter's real hostname:port




-----------------------------------------------------------------------------------------------------------------------------------------------------------------------




# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 52.66.205.128:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
    - "alert_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['52.66.205.128:9100']

  - job_name: 'jenkins'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['3.109.158.168:8080']
      
  - job_name: 'app' 
    metrics_path: '/metrics'
    static_configs:
      - targets: ['52.66.205.128:9100']

  - job_name: 'cAdvisor'
    static_configs:
      - targets: ['52.66.205.128:8080']

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['52.66.205.128:9093']
      
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://prometheus.io  # Target to probe with http.
        - https://prometheus.io  # Target to probe with http.
        - http://3.109.158.168:5000 # For Example:- 13.224.76.88:8080 or kubernetes port eg:- 30119 # Target to probe with http on port 8080. 
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 52.66.205.128:9115  # The blackbox exporter's real hostname:port




        

  
